// <auto-generated />
using System;
using CasinoAppBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasinoAppBackend.Migrations
{
    [DbContext(typeof(CasinoAppBackendDbContext))]
    [Migration("20260119111623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("TransactionNumberSequence")
                .StartsAt(100000L);

            modelBuilder.Entity("CasinoAppBackend.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("KycDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KycDocumentId")
                        .IsUnique();

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExternalSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSessionId")
                        .IsUnique();

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.KycDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpireDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("KycCheckDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KycCheckedBy")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("KycDocuments", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAgeVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKycVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelfExcluded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SelfExclusionEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelfExclusionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SelfExclusionStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerBanAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerBanAudits", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerDetailsAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDetailsAudits", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositMonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositWeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("LossDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LossMonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LossWeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingDepositDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingDepositDailyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingDepositMonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingDepositMonthlyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingDepositWeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingDepositWeeklyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingLossDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingLossDailyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingLossMonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingLossMonthlyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PendingLossWeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PendingLossWeeklyLimitStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerLimits", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerLimitAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("NewLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerLimitAudits", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerSelfExclusionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SelfExclusionEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SelfExclusionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SelfExclusionStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSelfExclusionAudits", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameRoundId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("NewBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TransactionNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionStatus")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameRoundId");

                    b.HasIndex("InsertedAt");

                    b.HasIndex("TransactionNumber")
                        .IsUnique();

                    b.HasIndex("AccountId", "InsertedAt", "TransactionType");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Account", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithOne("Account")
                        .HasForeignKey("CasinoAppBackend.Data.Account", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Admin", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("CasinoAppBackend.Data.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Admins_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Attachment", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.KycDocument", "KycDocument")
                        .WithOne("Attachment")
                        .HasForeignKey("CasinoAppBackend.Data.Attachment", "KycDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attachments_KycDocuments");

                    b.Navigation("KycDocument");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.GameSession", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GameSessions_Games");

                    b.HasOne("CasinoAppBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GameSessions_Users");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.KycDocument", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithOne("KycDocument")
                        .HasForeignKey("CasinoAppBackend.Data.KycDocument", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KycDocuments_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Player", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Country", "Country")
                        .WithMany("Players")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Players_Countries");

                    b.HasOne("CasinoAppBackend.Data.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("CasinoAppBackend.Data.Player", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Players_Users");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerBanAudit", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithMany("PlayerBanAudits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerBanAudits_Players");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerDetailsAudit", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithMany("PlayerDetailsAudits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerDetailsAudits_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerLimit", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithOne("PlayerLimit")
                        .HasForeignKey("CasinoAppBackend.Data.PlayerLimit", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerLimits_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerLimitAudit", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithMany("PlayerLimitAudits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerLimitAudits_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.PlayerSelfExclusionAudit", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Player", "Player")
                        .WithMany("PlayerSelfExclusionAudits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerSelfExclusionAudits_Players");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Transaction", b =>
                {
                    b.HasOne("CasinoAppBackend.Data.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Accounts");

                    b.HasOne("CasinoAppBackend.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Transactions_Games");

                    b.Navigation("Account");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Country", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.KycDocument", b =>
                {
                    b.Navigation("Attachment")
                        .IsRequired();
                });

            modelBuilder.Entity("CasinoAppBackend.Data.Player", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("KycDocument")
                        .IsRequired();

                    b.Navigation("PlayerBanAudits");

                    b.Navigation("PlayerDetailsAudits");

                    b.Navigation("PlayerLimit")
                        .IsRequired();

                    b.Navigation("PlayerLimitAudits");

                    b.Navigation("PlayerSelfExclusionAudits");
                });

            modelBuilder.Entity("CasinoAppBackend.Data.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
